<a href="https://colab.research.google.com/github/jyotidabass/MLP-by-hand--Visualize-architecture-with-python/blob/main/MLP_by_hand.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **HANDS ON MLP**



To get started, we'll install and import the NumPy library, which we'll use for our calculations. Next, we'll create two input data points (X1 and X2) and store them in a 2D array called "inputs."

Then, we'll define the weights (w1) and biases (b1) for the first hidden layer.


After that, we'll perform a dot product of the inputs and the first hidden layer's weights (w1), add the biases (b1), and store the result in z1. We'll then apply the ReLU activation function to the result (z1) and print it as Out1. This process helps us prepare the data for the next hidden layer.

In [5]:
!pip install numpy
import numpy as np

# Input data
X1 = np.array([2, 1, 2, 1])
X2 = np.array([-1, 1, 1, 2])
inputs = np.array([X1, X2])
# Weights and biases for each hidden layer
w1 = np.array([[1, 0, 1], [0, 1, -1], [-1, 1, 0], [1, 0, 0]])
b1 = np.array([1, 1, 0])

z1 = np.dot(inputs, w1) + b1

# Define the ReLU activation function
def relu(z):
    return np.maximum(0, z)
Out1= relu(z1)
print("Output: ", Out1)

Output:  [[2 4 1]
 [1 3 0]]


Now, we'll define the weights (w2) and biases (b2) for the second hidden layer. The dot product of the output of the first hidden layer (Out1) and the weights (w2) are computed and the biases (b2) are added.

This result is passed through the ReLU activation function and assigned to the variable Out2. Finally, the output of the second hidden layer is printed.

In [6]:
w2 = np.array([[0, -1, 0, -1], [-1, 1, 1, 0], [2, 0, 1, 0]])
b2 = np.array([1, 2, 1, 3])
z2 = np.dot(Out1, w2) + b2
Out2= relu(z2)
print("Output: ", Out2)

Output:  [[0 4 6 1]
 [0 4 4 2]]


Next, we'll define the weights (w3) and biases (b3) for the third hidden layer. The dot product of the output of the second hidden layer (Out2) and the weights (w3) are calculated, the biases (b3) are added, and the result is stored in z3.

Then, the ReLU activation function is applied to z3 to obtain the output of the third hidden layer (Out3).

In [7]:
w3 = np.array([[0, -1, -1], [-1, 1, 0], [-1, 1, 1], [2, 0, 0]])
b3 = np.array([5, 2, 3])
z3 = np.dot(Out2, w3) + b3
Out3= relu(z3)
print("Output: ", Out3)

Output:  [[ 0 12  9]
 [ 1 10  7]]


Now, we'll follow a similar process for the fourth hidden layer. We'll define the weights (w4) and bias (b4) for the output layer. It then calculates the dot product of the output of the third hidden layer (Out3) and the weights (w4), adds the bias (b4), and stores the result in z4.

The ReLU activation function is used on z4 to obtain the output of the output layer (Out4), which is then printed.


Next, we defined the sigmoid activation function, which takes a value x as input and returns the result of the sigmoid function applied to that value. Then, the sigmoid activation function is applied to the output of the output layer (Out4) and stored in the variable Z. Finally, the resulting value is printed as the "Final Output".

In [8]:
w4 = np.array([-1, 1, -1])
b4 = np.array([-2])

z4 = np.dot(Out3, w4) + b4
Out4= relu(z4)

print("Output: ", Out4)

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
Z= sigmoid(Out4)
print("Final Output: ",Z)

Output:  [1 0]
Final Output:  [0.73105858 0.5       ]
